[versions]
kotlin = "2.3.10"
mod-publish = "1.1.+"
architectury-loom = "1.11-SNAPSHOT"
shadow = "9.3.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }